language: dart
sudo: false

install:
  - npm install -g npm@2
  - npm install -g firebase-tools
  - npm install -g bower
  - npm install -g gulp-cli
  - npm install -g superstatic
  - pub global activate linkcheck

before_script:
  - chmod +x ./deploy/linkcheck.sh
  - chmod +x ./deploy/deploy-firebase.sh

script:
  - make build_travis
  - ./deploy/linkcheck.sh

deploy:
  - provider: script
    script: ./deploy/deploy-firebase.sh
    skip_cleanup: true
    on:
      branch: master
